# Site
name: "Domański Paweł"
title: "Domanski.io"
description: "Nazywam się Paweł Domański i oto moje miejsce w sieci. Tutaj znajdziesz wszystko co mnie interesuje, a czym chciałbym się podzielić z wami. Jestem mężem kochającej żony, ojcem dwóch synów, na co dzień pracuję jako administrator baz danych, a w wolnych chwilach sklejam modele."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /domanski_io
google_analytics: 'UA-176933448-1'
disqus: 'pawel-domanski'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: pawel@domanski.io

# Authors
authors:
  dexter:
    name: dexter
    display_name: Paweł
    gravatar: fc03109f514a34b0744511b333749936
    email: pawel@domanski.io
    web: https://domanski.io/
    twitter: https://twitter.com/pdomanski
    description: "Geek komputerowy, modelarz kartonowy, mąż kochającej żony i ociec dwóch synów. Na co dzień zajmuje się tym, żeby wszystkim żyło się lepiej, a wieczorami zapalony modelarz."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
